### ISSUE TITLE
Include this in Inkscape?

### ISSUE THREAD

**Issue by Moini** [fsmMLK/inkscapeCartesianPlotFunction2D#1]
Hi fsmMLK,

didn't test the extension yet, but it looks very useful! 

Is it possible to select if you want to show the grid/axes?

Would you like to make an issue at https://bugs.launchpad.net/inkscape and to propose this as an improvement to the existing extension? As long as the grids can be turned off, I think many people would like to see your improvements in the program itself.

**Comment by fsmMLK** [comment]
Yes, you can select.

If you check 'Draw Cartesian plane', it will draw the Cartesian plane too. Then, if you go to the 'Axes Configuration' tab, you can choose if  you want to show/hide the grids in x/y directions independently by (un)checking the 'Add grid to X axis' or  'Add grid to Y axis'.

**Comment by Moini** [comment]
Then I think it's definitely worth asking if it could be included :) Thanks for answering!
