### ISSUE TITLE
Edit existing plots

### ISSUE THREAD

**Issue by horror-vacui** [fsmMLK/inkscapeCartesianPlotFunction2D#6]
Is there a way to edit existing plots? Or is it possible to dump the code which is generated from the GUI input, so that I could edit them later and recreate the plots?

Use case: I should have edit some plots, i've created months ago. I have no idea about the exact function i have used, so I have to do some trial and error. I've also got 6 plots on each other, so it is time consuming to recreate them. I do not know whether inkscape allows to store these objects in an editable form, but I would be happy if some code could have been dumped, which could be reused somehow to recreate the plot.

**Comment by fsmMLK** [comment]
Currently it is not possible to do that. I will carefully take a look at this in future releases.

**Comment by fsmMLK** [comment]
The main issue with updating the plot is that there is no way of updating the GUI with the information from a previously created plots. I can add XML attributes to the created plot, but there is no way (that I am aware of) of sending that information to the GUI of the extension.
