### ISSUE TITLE
Error when the "Draw cartesian plane" setting is ticked.

### ISSUE THREAD

**Issue by pilgrimlyieu** [fsmMLK/inkscapeCartesianPlotFunction2D#8]
![2021-08-19_21-35-52](https://user-images.githubusercontent.com/80107081/130078893-2ef7e3be-0a99-472c-88e9-c09b19cb4399.png)
![2021-08-19_21-36-01](https://user-images.githubusercontent.com/80107081/130078906-298880ae-6cc7-4be3-9ede-8935afff8f51.png)
![2021-08-19_21-36-09](https://user-images.githubusercontent.com/80107081/130078911-130b67b0-a7d7-42e0-8dcf-63ee9dce6213.png)
![2021-08-19_21-36-15](https://user-images.githubusercontent.com/80107081/130078913-795560d7-1012-422b-96d8-ed0f942f3696.png)
![2021-08-19_21-36-52](https://user-images.githubusercontent.com/80107081/130078918-45aa00ac-4d75-4f65-a242-3826561574bb.png)

**Comment by fsmMLK** [comment]
There is an issue with recente siunitx package. Please see these threads to solve it.

https://github.com/fsmMLK/inkscapeCircuitSymbols/issues/27

https://github.com/fsmMLK/inkscapeMadeEasy/issues/14#issue-941914854

**Comment by pilgrimlyieu** [comment]
Thanks you indeed! It works now! Also thanks your amazing work!

**Comment by pilgrimlyieu** [comment]
Thanks you indeed! It works now! Also thanks your amzaing work!

**Comment by pilgrimlyieu** [comment]
Thanks you indeed! It works now! Also thanks your amazing work!

**Comment by fsmMLK** [comment]
updated inkscapemadeeasy to fix this issue
